Tidy up paths for BLAST, USEARCH, UniProt.
We now expect to find the BLAST and USEARCH
executables in the system path, while the location
of the UniProt database can be specified at
'make install' time.

diff --git a/lib/cryptosite/config/Makefile b/lib/cryptosite/config/Makefile
--- a/lib/cryptosite/config/Makefile
+++ b/lib/cryptosite/config/Makefile
@@ -9,5 +9,7 @@ install: ${CONFIG}
 
 ${CONFIG}::
 	@if [ ! -d ${PY} ]; then mkdir -p ${PY}; fi
+	@if [ ! -e ${UNIPROT} ]; then echo "Cannot find UniProt database as ${UNIPROT}; set the make UNIPROT variable to its location"; exit 1; fi
 	echo "datadir=r'${DATADIR}'" > $@
+	echo "uniprot=r'${UNIPROT}'" >> $@
 	python -m py_compile $@
